# Generated by Django 3.1.2 on 2021-02-19 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
    ]
