# Generated by Django 3.1 on 2020-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_image',
            field=models.FileField(upload_to=''),
        ),
    ]
