# Generated by Django 3.1 on 2020-09-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_auto_20200905_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='gpa',
        ),
    ]
