# Generated by Django 3.1 on 2020-09-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_nearbyrestaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyrestaurants',
            name='restaurant_url',
            field=models.URLField(default='000000', max_length=250),
        ),
    ]
