# Generated by Django 3.1 on 2020-09-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_nearbyrestaurants_restaurant_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NearbyRestaurants',
            new_name='NearbyRestaurant',
        ),
    ]
