# Generated by Django 3.1.2 on 2020-10-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0009_nearbyrestaurant_restuarant_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('cityid', models.AutoField(db_column='CityId', primary_key=True, serialize=False)),
                ('city', models.CharField(db_column='City', max_length=100)),
                ('state', models.CharField(db_column='State', max_length=2)),
                ('region', models.CharField(db_column='Region', max_length=2)),
            ],
            options={
                'db_table': 'Cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('institutionid', models.AutoField(db_column='InstitutionId', primary_key=True, serialize=False)),
                ('unitid', models.CharField(blank=True, db_column='UNITID', max_length=20, null=True)),
                ('opeid', models.CharField(blank=True, db_column='OPEID', max_length=20, null=True)),
                ('opeid6', models.CharField(blank=True, db_column='OPEID6', max_length=20, null=True)),
                ('instname', models.CharField(db_column='InstName', max_length=200)),
                ('accredagency', models.CharField(db_column='AccredAgency', max_length=200)),
                ('insturl', models.CharField(blank=True, db_column='InstURL', max_length=200, null=True)),
                ('pricecalcurl', models.CharField(blank=True, db_column='PriceCalcURL', max_length=200, null=True)),
                ('statefips', models.CharField(blank=True, db_column='StateFIPS', max_length=30, null=True)),
                ('maincampus', models.TextField(blank=True, db_column='MainCampus', null=True)),
                ('numberofbranches', models.CharField(blank=True, db_column='NumberOfBranches', max_length=2, null=True)),
                ('predominantdegrees', models.CharField(blank=True, db_column='PredominantDegrees', max_length=1, null=True)),
                ('highestdegree', models.CharField(blank=True, db_column='HighestDegree', max_length=1, null=True)),
                ('ownership', models.CharField(blank=True, db_column='Ownership', max_length=1, null=True)),
                ('distanceonly', models.TextField(blank=True, db_column='DistanceOnly', null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('locale', models.CharField(blank=True, db_column='Locale', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Institutions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zipcodes',
            fields=[
                ('zipcodeid', models.AutoField(db_column='ZipCodeId', primary_key=True, serialize=False)),
                ('zipcode', models.CharField(db_column='ZipCode', max_length=10)),
            ],
            options={
                'db_table': 'ZipCodes',
                'managed': False,
            },
        ),
    ]
