# Generated by Django 3.1.2 on 2020-10-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0010_auto_20201025_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NearbyRestaurant',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
