# Generated by Django 3.1.2 on 2020-11-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0017_auto_20201027_0401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutions',
            options={'managed': False, 'ordering': ['maincampus']},
        ),
    ]
