# Generated by Django 3.1.2 on 2020-11-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0018_auto_20201104_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutions',
            options={'managed': True, 'ordering': ['maincampus']},
        ),
    ]
