# Generated by Django 3.1.2 on 2020-11-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0020_auto_20201112_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutions',
            name='favorites',
        ),
    ]
