# Generated by Django 3.1.2 on 2020-11-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201021_0049'),
        ('universities', '0021_auto_20201112_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutions',
            name='favorite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorites', to='users.Profile'),
        ),
    ]
