# Generated by Django 3.1.2 on 2020-11-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0022_auto_20201112_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutions',
            options={'managed': False, 'ordering': ['maincampus']},
        ),
    ]
