# Generated by Django 3.1.2 on 2020-11-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0025_auto_20201113_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutions',
            options={'managed': False, 'ordering': ['maincampus']},
        ),
    ]
