# Generated by Django 3.1.2 on 2020-11-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0026_auto_20201113_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutions',
            options={'managed': True, 'ordering': ['maincampus']},
        ),
    ]
