# Generated by Django 3.1.2 on 2020-11-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0027_auto_20201115_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutions',
            options={'managed': False, 'ordering': ['maincampus']},
        ),
    ]
