# Generated by Django 3.1.2 on 2020-11-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0028_auto_20201116_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('climateid', models.AutoField(db_column='ClimateId', primary_key=True, serialize=False)),
                ('longitude', models.FloatField(db_column='Longitude')),
                ('latitude', models.FloatField(db_column='Latitude')),
                ('mintemp', models.FloatField(db_column='MinTemp')),
                ('avgtemp', models.FloatField(db_column='AvgTemp')),
                ('maxtemp', models.FloatField(db_column='MaxTemp')),
                ('zipcode', models.CharField(blank=True, db_column='ZipCode', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Climate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crimeid', models.AutoField(db_column='CrimeId', primary_key=True, serialize=False)),
                ('msa', models.CharField(db_column='MSA', max_length=150)),
                ('violentcrimes', models.FloatField(blank=True, db_column='ViolentCrimes', null=True)),
                ('propertycrimes', models.FloatField(blank=True, db_column='PropertyCrimes', null=True)),
            ],
            options={
                'db_table': 'Crime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('earningid', models.AutoField(db_column='EarningId', primary_key=True, serialize=False)),
                ('opeid', models.CharField(db_column='OPEID', max_length=15)),
                ('degree_level', models.CharField(blank=True, db_column='Degree_Level', max_length=2, null=True)),
                ('oneyear50pct', models.FloatField(blank=True, db_column='OneYear50Pct', null=True)),
                ('fiveyear50pct', models.FloatField(blank=True, db_column='FiveYear50Pct', null=True)),
                ('tenyear50pct', models.FloatField(blank=True, db_column='TenYear50Pct', null=True)),
            ],
            options={
                'db_table': 'Earnings',
                'managed': False,
            },
        ),
    ]
