# Generated by Django 3.1.2 on 2020-11-21 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0029_climate_crime_earnings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='crime',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='earnings',
            options={'managed': True},
        ),
    ]
