# Generated by Django 3.1.2 on 2020-11-21 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0030_auto_20201121_0347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='crime',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='earnings',
            options={'managed': False},
        ),
    ]
